export const GET_250_MOVIES = "GET_250_MOVIES";
export const GET_100_MOVIES = "GET_100_MOVIES";
export const GET_AWAIT_MOVIES = "GET_AWAIT_MOVIES";
export const GET_250_ISLOADING = "GET_250_ISLOADING";
export const GET_100_ISLOADING = "GET_100_ISLOADING";
export const GET_AWAIT_ISLOADING = "GET_AWAIT_ISLOADING";
